server:
  port: 8081
storage:
  type: file-system
  online-prefix: http://127.0.0.1:8081/
  location: D:/temp/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/journey?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      static-locations: file:${storage.location},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  security:
    user:
      name: simon
      password: simon123
logging:
  level:
    org.springframework.security: info
    com.rhymesun.journey.blog: debug
